{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1805.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"workstage\",\"department\",\"work type\",\"work category\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "__LastRPTime",
        "value": "133341862016183254"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "40d41add-bf60-4d7d-8394-fb9a1fbef829",
        "fromColumn": "Date",
        "fromTable": "workstage",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9608c658-c48f-4b34-abec-6ba10a30076b"
      },
      {
        "name": "25c57943-aa9e-44fd-a0ab-0173f623e9e5",
        "fromColumn": "statusDate",
        "fromTable": "workstage",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b42d8e60-53b5-41a0-919f-adc0dd90887d"
      },
      {
        "name": "a11257ef-e388-4a52-bafb-3f3067fd8978",
        "fromColumn": "createdAt",
        "fromTable": "work type",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6558ef3a-8fd7-4357-896f-39d9700014e3"
      },
      {
        "name": "2556b08d-4b43-4395-8560-7be1a1fbdf1f",
        "fromColumn": "updatedAt",
        "fromTable": "work type",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_61419727-8b50-4e8a-9659-ae2bb9109f27"
      },
      {
        "name": "32623417-9cf1-4ba0-8237-13ef8a7dd078",
        "fromColumn": "createdAt",
        "fromTable": "work category",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3b960f6e-e952-43bb-b668-44aff1f46f49"
      },
      {
        "name": "72f22608-0d6a-4e50-a4e4-270437c370c8",
        "fromColumn": "updatedAt",
        "fromTable": "work category",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_846698f0-1286-41c5-8b28-6d29cd55604b"
      },
      {
        "name": "c123ee6b-a2a6-4359-96d8-7d22482871f2",
        "fromColumn": "departmentId",
        "fromTable": "workstage",
        "toColumn": "id",
        "toTable": "department"
      },
      {
        "name": "790e36d7-f736-48e4-b193-55739d150137",
        "fromColumn": "workType",
        "fromTable": "workstage",
        "toColumn": "id",
        "toTable": "work type"
      },
      {
        "name": "670f550e-cace-43a6-997f-e9938b4a2311",
        "fromColumn": "workCategory",
        "fromTable": "workstage",
        "toColumn": "id",
        "toTable": "work category"
      }
    ],
    "roles": [
      {
        "name": "ORG_LEVEL_SECURITY",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7ce6879680c94e32af687682bb5d9691"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "workstage",
            "filterExpression": "workstage[org] = USERNAME()"
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "workstage",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f17a1651-0030-422a-bc90-ed148b754de6",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8863d263-0eea-48b1-93d7-3e06d7557918",
            "sourceColumn": "org",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f4e37d01-bc83-48d5-9589-e88cb08ec3f6",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a17cd020-0645-468a-9a67-163f4cbf6221",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_9608c658-c48f-4b34-abec-6ba10a30076b"
                },
                "isDefault": true,
                "relationship": "40d41add-bf60-4d7d-8394-fb9a1fbef829"
              }
            ]
          },
          {
            "name": "statusDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6aa987ad-e9dd-4c2b-9293-46f1a7ba69f4",
            "sourceColumn": "statusDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b42d8e60-53b5-41a0-919f-adc0dd90887d"
                },
                "isDefault": true,
                "relationship": "25c57943-aa9e-44fd-a0ab-0173f623e9e5"
              }
            ]
          },
          {
            "name": "priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cb78bade-20c2-4009-bd10-e8d7dd1de193",
            "sourceColumn": "priority",
            "summarizeBy": "sum"
          },
          {
            "name": "departmentId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59635189-c9a5-4de9-b8ac-6268fa29b95f",
            "sourceColumn": "departmentId",
            "summarizeBy": "none"
          },
          {
            "name": "workType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "250fb44a-56e6-4975-b455-e8f88c2ca0e2",
            "sourceColumn": "workType",
            "summarizeBy": "none"
          },
          {
            "name": "workCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07164fca-3029-4103-b48b-a0080b9f3015",
            "sourceColumn": "workCategory",
            "summarizeBy": "none"
          },
          {
            "name": "calculatedDepartment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(ISBLANK(RELATED(department[id])), \"(No Department)\", RELATED(department[name]))",
            "isDataTypeInferred": true,
            "lineageTag": "83a040b4-700d-4865-a415-52af95f95ab5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "e6edcabb-2a77-44ee-a373-0bcf1a5e84b5",
        "partitions": [
          {
            "name": "workstage-84885e36-f862-4a43-8043-1777db438d5d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"127.0.0.1,1433\", \"mentor_database\"),",
                "    dbo_workstage = Source{[Schema=\"dbo\",Item=\"workstage\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_workstage,{\"id\", \"org\", \"status\", \"createdAt\", \"statusDate\", \"priority\", \"departmentId\", \"workType\", \"workCategory\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each ([status] <> null)),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Filtered Rows\",{{\"createdAt\", \"Date\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ace8a058-3b17-4aed-b802-a0eb09d6e94b",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "22900400-cdce-49e4-a3ec-e9a3a3cd88fc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2963f955-271f-455a-b21e-5f816bbef108",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "afaacf04-0e72-4a6a-8928-27229db30989",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c403bb40-faf6-4a15-b831-c43221addbb2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b6341944-e313-48b4-8a9b-429d272206cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "41a218f6-1058-4c5a-a9ae-b3f45896e7d3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0805599b-3e7a-4176-a444-2d8dc8c3f2a6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9f1f28b4-5c6b-4539-a9cb-63f76d8d7429",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d4bc35e0-35f0-4d11-a8b3-356e2b2144df",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0ba32596-5dad-4d74-9662-74edaa62a2cb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4782a3e8-e228-489f-bdc1-99a5bac4a379",
                "ordinal": 3
              }
            ],
            "lineageTag": "a157cc77-361d-47b1-8a12-866b96335c38"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "a81c5f77-054c-45fd-beac-d3eb5745b98f",
        "partitions": [
          {
            "name": "DateTableTemplate_ace8a058-3b17-4aed-b802-a0eb09d6e94b-0eb327b2-c748-473c-b005-a3d982f18527",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_9608c658-c48f-4b34-abec-6ba10a30076b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "69f8b850-d158-48ac-951f-cee3f1672894",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5e87e3b6-9f34-41de-bb08-918c7a16a40d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7f322bf2-c1fb-4d45-a016-8f2d33d9a3ae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f8201ba7-8420-432f-8f78-8c18d8b6403f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0476ce7d-17ff-43d9-80b1-5193975fb88a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cb5693e8-f7e7-4a0e-a425-6b9f17ddd86a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "69c93fb2-a9c0-4ff2-a4c2-193a98af4df8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "11ffd17b-17e1-44e7-a12f-cd7b0a86066c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "824cf75c-6a2d-4699-835b-19e50d3eb7d8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5b9faf41-2c83-42a5-b315-9ac256fb5698",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c30bcfcf-79ef-42da-9515-f7ae87296b35",
                "ordinal": 3
              }
            ],
            "lineageTag": "9df2cf02-0514-414f-a602-88c6a2370eed"
          }
        ],
        "isHidden": true,
        "lineageTag": "62428a6e-afcb-41c3-8ebf-a0a0f47e42d6",
        "partitions": [
          {
            "name": "LocalDateTable_9608c658-c48f-4b34-abec-6ba10a30076b-b1a99539-b6df-4c45-93ef-5304a1a0aeb2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('workstage'[Date])), 1, 1), Date(Year(MAX('workstage'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b42d8e60-53b5-41a0-919f-adc0dd90887d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3aacc2e3-9c34-41cb-8f86-1ed76728ce7c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "00719364-a934-4fe6-b069-e71d4711e846",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "39b07160-8848-42d3-b3ba-20fb4107a2ff",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "28869239-76a7-4177-ae59-6da82b02dfd7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "13a76eac-b925-419e-bb63-62691976cd9c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "938bb657-24bb-4981-ad6a-be503526fa86",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c37fc1fd-aee1-4a98-ba01-43dd7c1a5ea5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0cce6a9c-7f65-4273-8711-7c2ec1d3be97",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9e398011-9db5-466e-85bd-1dc7841ed766",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "354a466b-715e-4590-bb13-57ff39ebedba",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b4ecc06b-0bdd-4a4b-9823-6f4fdcead135",
                "ordinal": 3
              }
            ],
            "lineageTag": "b31cd66f-15d0-47a7-a8f7-275bb3c81544"
          }
        ],
        "isHidden": true,
        "lineageTag": "c7c28480-9e07-4ba9-9c1f-356cddf983d5",
        "partitions": [
          {
            "name": "LocalDateTable_b42d8e60-53b5-41a0-919f-adc0dd90887d-2a7b9dab-13ca-4947-8af6-b5e024291afe",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('workstage'[statusDate])), 1, 1), Date(Year(MAX('workstage'[statusDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "department",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bf36315-536d-4e85-8f1a-b67f414b017b",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73b71b06-efa0-497d-9307-57859479166c",
            "sourceColumn": "org",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "468b5138-6187-44c0-84a4-2e8afb9dc7ae",
            "sourceColumn": "name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d87a7900-b80e-4667-9d4e-7909bfd15bf3",
        "partitions": [
          {
            "name": "department-7c2e4340-dcc8-4a04-b14f-3a8f8ebe91c6",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"127.0.0.1,1433\", \"mentor_database\"),",
                "    dbo_department = Source{[Schema=\"dbo\",Item=\"department\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_department,{\"id\", \"name\", \"org\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "work type",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0c2735df-16be-4846-ae78-b36a4803a6ca",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f252e88-70e9-46e7-afd5-828859701105",
            "sourceColumn": "org",
            "summarizeBy": "none"
          },
          {
            "name": "type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55c59f40-f3c6-4d85-af21-bb0fec3e1cb2",
            "sourceColumn": "type",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a333ad0-ca35-4ef8-92af-0c75021b101b",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9fc4c7d6-2eaf-4362-a3bc-0296399bfcb0",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "createdAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "85e48ce8-7f80-4bca-a7ff-d22305044a99",
            "sourceColumn": "createdAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_6558ef3a-8fd7-4357-896f-39d9700014e3"
                },
                "isDefault": true,
                "relationship": "a11257ef-e388-4a52-bafb-3f3067fd8978"
              }
            ]
          },
          {
            "name": "updatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1ffe525a-f942-44a2-858c-2508af9da3c2",
            "sourceColumn": "updatedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_61419727-8b50-4e8a-9659-ae2bb9109f27"
                },
                "isDefault": true,
                "relationship": "2556b08d-4b43-4395-8560-7be1a1fbdf1f"
              }
            ]
          },
          {
            "name": "dataStoreId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "513619a2-19cf-43ad-b11d-757bfd39aa21",
            "sourceColumn": "dataStoreId",
            "summarizeBy": "none"
          },
          {
            "name": "foreignId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "285e496f-e78a-48f3-a824-8f40a0efd94f",
            "sourceColumn": "foreignId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1a124dc7-c523-4ce4-be2d-d466fedcd97c",
        "partitions": [
          {
            "name": "work type-1d54672b-922c-4ed4-9984-f037d8cdd092",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"127.0.0.1,1433\", \"mentor_database\"),",
                "    dbo_systemlookup = Source{[Schema=\"dbo\",Item=\"systemlookup\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_systemlookup, each ([type] = \"WORK_TYPE\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6558ef3a-8fd7-4357-896f-39d9700014e3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "14225bf4-73e3-4d21-b309-19daf83a9820",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9bd68cbc-c43b-4ec2-9a98-79a18f4e0a83",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4d69fa6c-77db-4224-9a9f-7e185ad35921",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e561c890-2a41-4cd2-a349-b1ff9cde3bc9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ac1d496c-d806-4237-a3fc-64a558201bfc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3375d91b-c15d-49b7-8701-b784cbc12370",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "58e41b8a-f1e5-48e8-bb98-110653136b95",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d31f0952-e445-4a47-9274-88127e56e9cd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "123d6c2a-0f31-4516-baff-72613e28d451",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "177d3567-0620-409a-b925-55bef30eecf3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c0f54e37-a2a9-4e25-8486-e73f5b0785a1",
                "ordinal": 3
              }
            ],
            "lineageTag": "27c84f18-09f7-4d59-96d5-759698dc2acd"
          }
        ],
        "isHidden": true,
        "lineageTag": "c183339a-3c2f-4193-8c4e-ae38d1b2819f",
        "partitions": [
          {
            "name": "LocalDateTable_6558ef3a-8fd7-4357-896f-39d9700014e3-820f7db6-f0b1-439e-b2a8-9b07ee71c581",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('work type'[createdAt])), 1, 1), Date(Year(MAX('work type'[createdAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_61419727-8b50-4e8a-9659-ae2bb9109f27",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "620303dd-5e5d-44d4-879d-4f8802cc82ca",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "500b5f83-6446-4b1a-9b11-f403904f25f1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "142663ac-0c52-425f-b9cd-1257f3c0216d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d6e2d617-234e-4a38-b9ca-4b690e204065",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "900d878b-2739-457f-8a77-c00cfc856873",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b5943f6d-be0f-4243-9c81-eaabff9a8d7b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f2b667d0-77ff-4c65-818b-be8df4c52988",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "db1821a6-8e22-4e77-8086-1f6a818be25b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8a549a65-5781-4dc5-9356-f9b777c891f3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a934c0e7-db7b-420b-9e57-260dc15407b2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a4758353-88ce-47f6-b389-a1832f80bc69",
                "ordinal": 3
              }
            ],
            "lineageTag": "4f4fbae8-9bfd-4669-acaa-8db22f1a27ab"
          }
        ],
        "isHidden": true,
        "lineageTag": "a9f4e6a6-c3fb-47ba-98e9-be292fef3931",
        "partitions": [
          {
            "name": "LocalDateTable_61419727-8b50-4e8a-9659-ae2bb9109f27-fcaedc97-64ea-4a36-94cb-bacd10aacb94",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('work type'[updatedAt])), 1, 1), Date(Year(MAX('work type'[updatedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "work category",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6daf9da0-8d36-42ee-964c-6dae98623414",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b8fe372-3b0c-4993-b02d-4e43ef82710c",
            "sourceColumn": "org",
            "summarizeBy": "none"
          },
          {
            "name": "type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4bccf1a-a7b4-4eb4-8595-f65b2cc763a5",
            "sourceColumn": "type",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1438a37b-89c2-4971-aeb8-90491d357f55",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ccf1ff36-0f40-438d-bded-39d2b880253a",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "createdAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "89118919-2b25-4342-a6f6-62e4cf926369",
            "sourceColumn": "createdAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3b960f6e-e952-43bb-b668-44aff1f46f49"
                },
                "isDefault": true,
                "relationship": "32623417-9cf1-4ba0-8237-13ef8a7dd078"
              }
            ]
          },
          {
            "name": "updatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e159b92f-8536-4232-ba3f-0ae2a403ff68",
            "sourceColumn": "updatedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_846698f0-1286-41c5-8b28-6d29cd55604b"
                },
                "isDefault": true,
                "relationship": "72f22608-0d6a-4e50-a4e4-270437c370c8"
              }
            ]
          },
          {
            "name": "dataStoreId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d20797d-abbd-4a61-88b5-fe593e7040fb",
            "sourceColumn": "dataStoreId",
            "summarizeBy": "none"
          },
          {
            "name": "foreignId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efa7dffd-5e59-4a8a-87ec-8c4f90d72fcd",
            "sourceColumn": "foreignId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cdaab5cc-5c2c-4e49-bdeb-01505a47e044",
        "partitions": [
          {
            "name": "work category-6214e057-3e84-467d-b5ff-6d7e8ed5f244",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"127.0.0.1,1433\", \"mentor_database\"),",
                "    dbo_systemlookup = Source{[Schema=\"dbo\",Item=\"systemlookup\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_systemlookup, each ([type] = \"WORK_CATEGORY\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3b960f6e-e952-43bb-b668-44aff1f46f49",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "aa579e39-8c2d-4cbb-9da9-5b791607d936",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c7c908ec-c86c-4982-a9fd-c7935e5050bf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "649b5e4a-b19b-4c07-82f1-1c7997b6d5c8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f21464c0-f48f-4cb1-93cc-5b3be3878aa3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "967bcbb5-e3c3-4fa4-8994-3953e99402f1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "df676146-e3aa-4f3f-918c-9d0b8f1f3081",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f7f4ed9e-c40f-4b4d-a578-19e832cc264b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8b0cf72c-fa9d-4540-9f06-45c78c88db98",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "be72f005-5419-4987-a0a1-d61c1ba6202f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a3fc44a0-cec5-4a49-8df2-6a2984db7440",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "19ed1c46-36d2-4d5b-9aad-f71db04c0be9",
                "ordinal": 3
              }
            ],
            "lineageTag": "ede6e363-8ff4-48fe-ad82-ebb24d5188b6"
          }
        ],
        "isHidden": true,
        "lineageTag": "f483c727-7d46-4d3a-9f70-7827f1d9d932",
        "partitions": [
          {
            "name": "LocalDateTable_3b960f6e-e952-43bb-b668-44aff1f46f49-8244dbe9-4cb6-449f-9433-56de72d29733",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('work category'[createdAt])), 1, 1), Date(Year(MAX('work category'[createdAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_846698f0-1286-41c5-8b28-6d29cd55604b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "832b88aa-5e9b-4ad9-ba7c-9af14c383ec4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f69a8133-773f-4e47-bb91-79dad385b2e4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "736bdea5-3559-427a-905f-e6b06e4592fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a5af01a8-a5eb-475b-94cf-ba76195d129c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c11e42ba-0887-4737-baf3-8ef26863f2af",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6fbf30be-e5da-4c2e-822f-4658f4aa1059",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b9acb111-67d5-4859-85a1-7ac7f963f242",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "eec47da1-ddda-48b2-86a6-97cc95d8c610",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4e1c8dbc-2d9a-41dc-8b70-944a58c32980",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "fb55e7c6-ce6f-4c9c-adf6-d001891ad8b1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "396b833b-9882-47d7-b7fd-b594b8da72c2",
                "ordinal": 3
              }
            ],
            "lineageTag": "37020131-fedf-4dd5-84e4-b52ac15cfa89"
          }
        ],
        "isHidden": true,
        "lineageTag": "6166fc49-2ce2-4d3e-8fcf-d02414cc1973",
        "partitions": [
          {
            "name": "LocalDateTable_846698f0-1286-41c5-8b28-6d29cd55604b-b91cf2e7-4750-4875-938b-07e1bc35206c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('work category'[updatedAt])), 1, 1), Date(Year(MAX('work category'[updatedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}