{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"workstage\",\"department\",\"workcategory (2)\",\"systemlookup (2)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1805.0 (23.12)"
      },
      {
        "name": "__LastRPTime",
        "value": "133341862221043027"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "ba1eba4e-b01f-4479-8140-6f7f93b94baf",
        "fromColumn": "statusDate",
        "fromTable": "workstage",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f49a48a8-8165-48f0-87dd-32538785da66"
      },
      {
        "name": "a17eff79-05eb-4f87-9cfa-d0be7f5dba12",
        "fromColumn": "createdAt",
        "fromTable": "department",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9945cca1-650d-4d60-b5eb-06657aef4d72"
      },
      {
        "name": "a21c74ea-9286-437b-bc2e-af930c10a21f",
        "fromColumn": "updatedAt",
        "fromTable": "department",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d6fc5cc8-54c4-4719-9412-2a787db22d83"
      },
      {
        "name": "f602166e-7610-4375-962c-8e3da8bfa765",
        "fromColumn": "departmentId",
        "fromTable": "workstage",
        "toColumn": "id",
        "toTable": "department"
      },
      {
        "name": "b2358182-e4d7-40d0-bd01-4795d59b9acd",
        "fromColumn": "Date",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_68c98868-836b-4b90-a547-4c7c7ea4613c"
      },
      {
        "name": "65eb3e65-5289-462f-81dc-dc54756c412f",
        "fromColumn": "ㅤ",
        "fromTable": "workstage",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e0c0afbf-a8fa-421f-9836-96332dba1f98"
      },
      {
        "name": "2feba214-8f05-47c5-bf4d-cdfedd8ad3f2",
        "fromColumn": "createdAt",
        "fromTable": "workcategory (2)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_86c4d15d-1fc4-485a-abd6-6d843c0e2a0e"
      },
      {
        "name": "2d841b4c-2848-4995-97aa-5b045841638a",
        "fromColumn": "updatedAt",
        "fromTable": "workcategory (2)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_36523510-a5f8-4ab5-8002-940f4667f3fe"
      },
      {
        "name": "ae44d186-3d6d-4cc1-88d9-4f1a459a38f8",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "workCategory",
        "fromTable": "workstage",
        "toColumn": "id",
        "toTable": "workcategory (2)"
      },
      {
        "name": "89f5a091-51b9-48be-84f5-90676142f684",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "workType",
        "fromTable": "workstage",
        "isActive": false,
        "toColumn": "id",
        "toTable": "workcategory (2)"
      },
      {
        "name": "35bd217b-5ede-4e95-a02b-ec3e487c42d7",
        "fromColumn": "createdAt",
        "fromTable": "systemlookup (2)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f608b07e-684f-49d7-9711-b443714e3eff"
      },
      {
        "name": "8af14aa0-2331-4bfb-81e8-6ec05c2ab2dc",
        "fromColumn": "updatedAt",
        "fromTable": "systemlookup (2)",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_658449bb-c6b5-4f89-8062-310009421a53"
      },
      {
        "name": "5ec332e6-7250-43c7-a298-c154b05439cf",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "workCategory",
        "fromTable": "workstage",
        "toColumn": "id",
        "toTable": "systemlookup (2)"
      },
      {
        "name": "aa15d93b-6c06-4102-8508-38c44a26cd63",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "workType",
        "fromTable": "workstage",
        "isActive": false,
        "toColumn": "id",
        "toTable": "systemlookup (2)"
      }
    ],
    "roles": [
      {
        "name": "ORG_LEVEL_SECURITY",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "37a37e6ff6f94b68919985399be71e35"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "workstage",
            "filterExpression": "workstage[org] = USERNAME()"
          },
          {
            "name": "department",
            "filterExpression": "department[org] = USERNAME()"
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_1a44ea68-77a5-49e4-a21a-0540d7eda6c8",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e090f002-6c1f-4506-9607-75f9fca87263",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a5e44295-2b46-4e41-bdd0-8db5b120a20b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "acf49887-43c5-442c-9360-a4be52b1835c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a4286bf5-f8ea-4405-8016-d4d591740407",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f6f1feee-5b84-4ac8-ad5f-ada1e21e8822",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "088b2189-ba8d-46e0-b9c6-eefcb5b21953",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b9f3faf2-e19a-4803-94aa-7f5857ffdaea",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c86eaf7a-f9b2-4993-9205-e04b3594b1fb",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f95ba599-c664-46c2-bbea-7dbc6390080f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "975dabd6-c4ea-4514-9d14-01505255a16b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4492981d-bbd2-4c71-aabf-7f8e3b114192",
                "ordinal": 3
              }
            ],
            "lineageTag": "72843c53-82f4-4ba9-bf62-daaffb3fcc7e"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "a07819da-3a01-4921-988f-bc587da5140a",
        "partitions": [
          {
            "name": "DateTableTemplate_1a44ea68-77a5-49e4-a21a-0540d7eda6c8-4892ca9c-a091-4941-b834-a0ff0dd603d3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "workstage",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Work Stages",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff43a778-a91f-4a66-9b61-1e7ffe3986b1",
            "sourceColumn": "Work Stages",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ba7c3b0-7f26-441b-bfd4-bba9824a33b0",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e112bf1a-e40b-4e30-9dd5-83955c0a320d",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "ㅤ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "7e33e369-fc18-4e1b-8617-b45c257bd093",
            "sourceColumn": "ㅤ",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e0c0afbf-a8fa-421f-9836-96332dba1f98"
                },
                "isDefault": true,
                "relationship": "65eb3e65-5289-462f-81dc-dc54756c412f"
              }
            ]
          },
          {
            "name": "statusDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "4b749160-2810-40a8-8ed7-a9c03ca6253b",
            "sourceColumn": "statusDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f49a48a8-8165-48f0-87dd-32538785da66"
                },
                "isDefault": true,
                "relationship": "ba1eba4e-b01f-4479-8140-6f7f93b94baf"
              }
            ]
          },
          {
            "name": "priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "741ebf2e-ff4d-43ac-9b43-1f452daca6d9",
            "sourceColumn": "priority",
            "summarizeBy": "sum"
          },
          {
            "name": "workType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55b5718e-2705-4ede-8a76-786eb2a93df7",
            "sourceColumn": "workType",
            "summarizeBy": "none"
          },
          {
            "name": "workCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "755909e2-24dc-44dc-a9a5-c1d8fee77a7d",
            "sourceColumn": "workCategory",
            "summarizeBy": "none"
          },
          {
            "name": "displayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29faddf5-cf33-4795-82c5-aff0c609dfa7",
            "sourceColumn": "displayName",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e12a805c-a78b-4466-a5f3-47d28778d453",
            "sourceColumn": "org",
            "summarizeBy": "none"
          },
          {
            "name": "workId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23759b08-fcea-4c2d-8828-85564e2023aa",
            "sourceColumn": "workId",
            "summarizeBy": "none"
          },
          {
            "name": "altId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "678377a5-5d14-40c7-a392-05491d7c3682",
            "sourceColumn": "altId",
            "summarizeBy": "none"
          },
          {
            "name": "departmentId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46aee543-30d9-4393-b453-5be7bd1fff8f",
            "sourceColumn": "departmentId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4c2d1257-a948-453c-ba1f-659a4c75023c",
        "partitions": [
          {
            "name": "workstage-ad0bcc19-a526-4dbe-87f1-9b00a2cef54a",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"127.0.0.1,1433\"),",
                "    mentor_database = Source{[Name=\"mentor_database\"]}[Data],",
                "    dbo_workstage = mentor_database{[Schema=\"dbo\",Item=\"workstage\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_workstage,{\"id\", \"org\", \"workId\", \"name\", \"altId\", \"status\", \"createdAt\", \"statusDate\", \"priority\", \"departmentId\", \"workType\", \"workCategory\", \"displayName\", \"department\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Other Columns\",{{\"createdAt\", \"ㅤ\"}, {\"id\", \"Work Stages\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_f49a48a8-8165-48f0-87dd-32538785da66",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "960e4449-ab5b-45c0-b9ff-74842b137e29",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f2667533-3b94-4d76-824a-818c96619601",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bdea9b02-b39a-4f60-8bb1-965a365e5d1b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "45c1168c-9bfa-49b0-80ef-0a6fd5bd7e42",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c0ec8da0-d7e3-4590-bdb1-d9e552042faf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "915e3c44-3a71-42a3-9417-7fe74019bc24",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7d6bafcd-2cd0-4b53-aa15-44ca4e526461",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c7ce235f-c5b2-45cb-b858-4256a9ebed27",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "28dec23b-eabb-4188-a4ff-ad4a960639c7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1f84850a-6ee1-4333-960d-e4975e3a19c8",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b1be8fb1-cb8b-45b4-aed2-3ca16dd4805e",
                "ordinal": 3
              }
            ],
            "lineageTag": "a337a77d-a1d5-4eed-ac79-4e04b8465ab5"
          }
        ],
        "isHidden": true,
        "lineageTag": "5a4e0220-1e0b-47e9-98ab-c8defff17a3e",
        "partitions": [
          {
            "name": "LocalDateTable_f49a48a8-8165-48f0-87dd-32538785da66-3b5c0752-ce38-49da-a7b3-fe60fcd8beea",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('workstage'[statusDate])), 1, 1), Date(Year(MAX('workstage'[statusDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "department",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58ec7e45-6e3b-41fe-bb3d-83f264df2db4",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12cccc61-7f72-42d9-bcfd-085f19ec16c3",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "createdAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2059b0fd-72a9-4e09-8108-407b6e314d24",
            "sourceColumn": "createdAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_9945cca1-650d-4d60-b5eb-06657aef4d72"
                },
                "isDefault": true,
                "relationship": "a17eff79-05eb-4f87-9cfa-d0be7f5dba12"
              }
            ]
          },
          {
            "name": "updatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "560e7736-e012-4fb3-ac29-8aeb518f6521",
            "sourceColumn": "updatedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d6fc5cc8-54c4-4719-9412-2a787db22d83"
                },
                "isDefault": true,
                "relationship": "a21c74ea-9286-437b-bc2e-af930c10a21f"
              }
            ]
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5f67553-2884-4afe-89e4-41a154ded95c",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4844d9a4-f82f-4c6e-bac2-4b3e2fe5b908",
            "sourceColumn": "org",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9e84b57a-6465-43ab-a9f0-5d1e709cb1a3",
        "partitions": [
          {
            "name": "department-30ca9f4c-74e5-473b-b671-12f40ede8aa9",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"127.0.0.1,1433\"),",
                "    mentor_database = Source{[Name=\"mentor_database\"]}[Data],",
                "    dbo_department = mentor_database{[Schema=\"dbo\",Item=\"department\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_department,{\"laborOffsetAccount\", \"laborOffsetExpenditureType\", \"createdBy\", \"updatedBy\", \"account\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_9945cca1-650d-4d60-b5eb-06657aef4d72",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1cf4cc39-8165-416a-a9ff-8bfec010b7f2",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5e208cad-2c8b-484e-8da8-dd962c91d955",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1fc4da3a-411b-40e8-b1f3-c7ddd5fe2820",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "191cd3db-fece-4a1b-9b44-f7969e54874a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9a3e6d90-4d22-44de-b614-2e77ad4d0e29",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "598ee33c-56d8-4641-80fa-c4a718a526bf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c59c1d4d-c91c-4798-a94f-bae1759411bb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "87a43cf2-eaa5-4406-82fc-5c8eaa48c2fe",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3167556e-a122-4f43-8043-98c07df88aa8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3c77ce4b-82c8-446d-bd28-9b1f6693a0fb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "dd56f563-89da-4330-9f0a-c097387713f7",
                "ordinal": 3
              }
            ],
            "lineageTag": "a7a1351c-60d7-45db-9329-a884c00dc5e5"
          }
        ],
        "isHidden": true,
        "lineageTag": "1f7d023e-9a3a-46e2-bbce-c53f07721d40",
        "partitions": [
          {
            "name": "LocalDateTable_9945cca1-650d-4d60-b5eb-06657aef4d72-3f101699-e9db-442c-be72-d41803a8d8a7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('department'[createdAt])), 1, 1), Date(Year(MAX('department'[createdAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d6fc5cc8-54c4-4719-9412-2a787db22d83",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "07e47565-99a2-49dd-b89d-84eaf1c5a2a7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3bd70cb2-924d-48d2-b81a-60658d9538e5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9a181556-7a3f-40d1-9c34-035512832f05",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6d24e7c3-a12c-4fb4-baf5-2240304d2c39",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c2863f76-a830-4323-97f2-8489d6ae27ce",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d71f93b2-f2e4-4918-912d-3052eee0f1d7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "86c56062-6acf-4a7e-8b72-db605ba94dca",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "deb9657f-ebb7-48e2-9b45-f05954dac90f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "17292c60-7063-4635-87e9-29d7c7f3fc4e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ccef023a-6827-4018-93c8-a4c70ed5bdce",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "198ce5a1-8117-4d5a-9f00-19e755980dc9",
                "ordinal": 3
              }
            ],
            "lineageTag": "297cffa8-ddfd-4e5c-a371-2da0dd286341"
          }
        ],
        "isHidden": true,
        "lineageTag": "71b812af-22ce-4a99-86eb-ae7e7f6b687e",
        "partitions": [
          {
            "name": "LocalDateTable_d6fc5cc8-54c4-4719-9412-2a787db22d83-0f229e91-04d3-4953-af1e-d5860d44d144",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('department'[updatedAt])), 1, 1), Date(Year(MAX('department'[updatedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3dd81763219f4e83acfe3f57292225ed"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d5e4c725-f5eb-4b26-908d-1d0a5913cdc9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_68c98868-836b-4b90-a547-4c7c7ea4613c"
                },
                "isDefault": true,
                "relationship": "b2358182-e4d7-40d0-bd01-4795d59b9acd"
              }
            ]
          }
        ],
        "lineageTag": "09add659-c9c5-4f3f-a660-0e8170b22b46",
        "partitions": [
          {
            "name": "Calendar-d280836f-f689-4bf3-a904-fb3d1ec0eaa0",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(TODAY() - 18250, TODAY())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_68c98868-836b-4b90-a547-4c7c7ea4613c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "694ac29c-d234-4b76-81df-e440309014be",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "46690512-3678-4832-b092-fc4865255979",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "762537dc-3199-43c6-9f01-db4b8d73a77a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4451c1af-7541-43e5-acc2-dd5cf4c51c9e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a9f0042b-4352-4cb7-841d-c2c3b16b384a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "10d5da70-a96a-43db-aae5-e98074f56f5a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1cc03756-8454-46b1-b788-69ca2a3e6a87",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "da093f2b-de53-47f2-ac3e-b564912b6567",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f326478c-bae6-488e-aaa0-ee6d3049385f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ee671bd5-54df-4fd4-957e-4671da1c4c5d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "716a7e26-ca48-4e04-b1f7-66f46a28f183",
                "ordinal": 3
              }
            ],
            "lineageTag": "737250fc-e5d9-4b81-9155-d91ead85e6a8"
          }
        ],
        "isHidden": true,
        "lineageTag": "08a0a7a9-d058-4faf-8d58-f434a8f9920c",
        "partitions": [
          {
            "name": "LocalDateTable_68c98868-836b-4b90-a547-4c7c7ea4613c-ed8cae96-a42a-44bb-8f68-65c538a27aa2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[Date])), 1, 1), Date(Year(MAX('Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e0c0afbf-a8fa-421f-9836-96332dba1f98",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c6623399-aaac-41c8-b1a6-c388a4928d17",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8b092657-3ac8-4730-af22-78d2dc6bbfcb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5abe356a-b7ac-4a15-a064-b2e5e2a1f05d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4fd2fd40-a93c-4445-8660-11bfe7b0664d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d2409232-241c-4ba4-95f7-f9bf564a13cd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "adb30325-e5ec-44e3-b617-6054d5749824",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8e2f0a7a-b460-46a1-adf6-1416289de220",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "88c62ca4-cea7-4d0d-9a15-6b45d6c8973e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8d2a8aad-0a82-4132-935c-e16c0a21c69a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "02b0fb04-d98a-42d7-b63f-2c7058c317b7",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "356010eb-8636-4ee4-a132-b62449de8d9f",
                "ordinal": 3
              }
            ],
            "lineageTag": "01558943-a81f-4b3c-a6a8-947a6bd99302"
          }
        ],
        "isHidden": true,
        "lineageTag": "2ff1ba71-30ea-4ba8-ae01-d6d8dd80389b",
        "partitions": [
          {
            "name": "LocalDateTable_e0c0afbf-a8fa-421f-9836-96332dba1f98-c7e5c903-7294-4c9b-9b09-1b03c9a9da4b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('workstage'[ㅤ])), 1, 1), Date(Year(MAX('workstage'[ㅤ])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "workcategory (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c8ef1f5-5fc3-4fe1-9d93-dddc9bfa21d6",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc72ffb5-6a33-4f44-8dc0-31995db1c6f5",
            "sourceColumn": "org",
            "summarizeBy": "none"
          },
          {
            "name": "type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9a5c144-cdbd-4ead-8e84-5ccb25157988",
            "sourceColumn": "type",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "900ee63f-8188-415d-befe-4a66fbc643de",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ee87b8b-82b6-4b72-9450-bbe525389d34",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "createdAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a535ac93-b341-4a84-8d0d-2152695e2b35",
            "sourceColumn": "createdAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_86c4d15d-1fc4-485a-abd6-6d843c0e2a0e"
                },
                "isDefault": true,
                "relationship": "2feba214-8f05-47c5-bf4d-cdfedd8ad3f2"
              }
            ]
          },
          {
            "name": "updatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ec8bb17c-615e-4d79-a856-1b625da0ca4f",
            "sourceColumn": "updatedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_36523510-a5f8-4ab5-8002-940f4667f3fe"
                },
                "isDefault": true,
                "relationship": "2d841b4c-2848-4995-97aa-5b045841638a"
              }
            ]
          },
          {
            "name": "dataStoreId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f28ba72c-f32e-44bc-8c6a-32f6daab4681",
            "sourceColumn": "dataStoreId",
            "summarizeBy": "none"
          },
          {
            "name": "foreignId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cbf3299-7746-4ec5-ab6f-67954cc4b8ed",
            "sourceColumn": "foreignId",
            "summarizeBy": "none"
          },
          {
            "name": "createdBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb914670-f9b1-4c45-9f3e-dffb823edd46",
            "sourceColumn": "createdBy",
            "summarizeBy": "none"
          },
          {
            "name": "updatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f484dfa9-e9a4-4bae-bc23-f067b4a71bed",
            "sourceColumn": "updatedBy",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7aba7878-6007-43cb-91b5-132e66db17a0",
        "partitions": [
          {
            "name": "workcategory (2)-fd19d6ab-1730-414a-8d9b-81e05904a5ba",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"127.0.0.1,1433\"),",
                "    mentor_database = Source{[Name=\"mentor_database\"]}[Data],",
                "    dbo_systemlookup = mentor_database{[Schema=\"dbo\",Item=\"systemlookup\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_systemlookup, each ([type] = \"WORK_CATEGORY\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_86c4d15d-1fc4-485a-abd6-6d843c0e2a0e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7602ab1d-b801-4c54-a9e6-e4a508a457ed",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3d7744b1-c6cf-41f3-8f02-04c013b6852e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "56095a81-5ffc-40a6-a8a9-24e01a6bd13f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ecaad52d-f5b0-4f70-8f0e-ac5f3b975096",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f9e5c24f-7fa9-4399-a637-0fb3c298fdca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "64723399-2634-4080-ab31-6fc991e91635",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1e450f0c-7a70-4d42-9bb5-9d7301c643fe",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "54e1d50d-aa95-43f8-a950-ad483c41f5be",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c2d49392-3ecf-4f31-9c50-f4820f97467f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f3359678-b653-45fc-ab38-bb5ff8b9efe2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "dcc4cc32-5f59-4645-af92-c81d027f4258",
                "ordinal": 3
              }
            ],
            "lineageTag": "2900b945-ba6f-4705-a147-8e491bb8e566"
          }
        ],
        "isHidden": true,
        "lineageTag": "71365a80-a6a7-4a84-98f4-8380fb985fae",
        "partitions": [
          {
            "name": "LocalDateTable_86c4d15d-1fc4-485a-abd6-6d843c0e2a0e-05d56d45-c8ca-4676-bfc8-add98ccbb21c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('workcategory (2)'[createdAt])), 1, 1), Date(Year(MAX('workcategory (2)'[createdAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_36523510-a5f8-4ab5-8002-940f4667f3fe",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e6bff4dc-605f-4fa1-b83c-7ef44acd6d4c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1088f88e-901e-4b7d-a1e7-cebd33c08db9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "10fa7efd-ff84-416e-9fa9-c08e77d40d4d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4a26e799-ef8d-4089-b49d-fd61e252b52a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1f2bdd3a-cf3d-4bb1-a53d-38aec226e1f8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4b168af6-9539-4837-9a47-6316f8ce2b67",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d76808fc-eb97-434d-b61e-a4b77ede5089",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d0fd4214-3d6f-47b2-bd15-9a5f88604ce9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e7df5152-4f90-40aa-93d7-d7b453371041",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "74c5001c-6a1f-4914-8860-f092d0d1e857",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2be23ed8-fab9-4243-b941-e4068657fd7d",
                "ordinal": 3
              }
            ],
            "lineageTag": "5b759ee8-00d8-4cb2-9a7d-a435e005a4f0"
          }
        ],
        "isHidden": true,
        "lineageTag": "c4724259-eee3-4f4b-bbec-416c1d86d9df",
        "partitions": [
          {
            "name": "LocalDateTable_36523510-a5f8-4ab5-8002-940f4667f3fe-262794f8-f27e-41dc-89c1-bd012532e71f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('workcategory (2)'[updatedAt])), 1, 1), Date(Year(MAX('workcategory (2)'[updatedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "systemlookup (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7efcdad-12a7-4485-8e73-56d674e5088c",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79efd854-22a0-4d08-84bd-38e76e56cbd6",
            "sourceColumn": "org",
            "summarizeBy": "none"
          },
          {
            "name": "type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b97ad8d5-7cdc-4456-b19e-df87ad5eecba",
            "sourceColumn": "type",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0dcdbdc7-7b3d-40df-8ba2-6fcf108e3a32",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f8128cc-2ca9-4230-ac24-ba781fa5bbd3",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "createdAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9c3308d4-86e7-4123-8250-cc4dfb05fa50",
            "sourceColumn": "createdAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f608b07e-684f-49d7-9711-b443714e3eff"
                },
                "isDefault": true,
                "relationship": "35bd217b-5ede-4e95-a02b-ec3e487c42d7"
              }
            ]
          },
          {
            "name": "updatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f57c051f-fce8-4040-86c5-937a7ce5e31d",
            "sourceColumn": "updatedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_658449bb-c6b5-4f89-8062-310009421a53"
                },
                "isDefault": true,
                "relationship": "8af14aa0-2331-4bfb-81e8-6ec05c2ab2dc"
              }
            ]
          },
          {
            "name": "dataStoreId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adafc68d-50d1-4536-a7ec-a415feee1355",
            "sourceColumn": "dataStoreId",
            "summarizeBy": "none"
          },
          {
            "name": "foreignId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6124373a-3706-433c-a2a5-ec0a47518c7a",
            "sourceColumn": "foreignId",
            "summarizeBy": "none"
          },
          {
            "name": "createdBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af648d21-6180-41f1-8563-c611a33737ba",
            "sourceColumn": "createdBy",
            "summarizeBy": "none"
          },
          {
            "name": "updatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2305161b-1e7c-4853-99b6-71107ce8bfa4",
            "sourceColumn": "updatedBy",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8a037afb-52c2-46cc-8e8c-f5b595ac21e6",
        "partitions": [
          {
            "name": "systemlookup (2)-22d7aadb-f313-4cc3-a1ce-e0056cfa41be",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"127.0.0.1,1433\"),",
                "    mentor_database = Source{[Name=\"mentor_database\"]}[Data],",
                "    dbo_systemlookup = mentor_database{[Schema=\"dbo\",Item=\"systemlookup\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_systemlookup, each ([type] = \"WORK_TYPE\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_f608b07e-684f-49d7-9711-b443714e3eff",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "593ab174-69fe-4bcc-83cc-9cef817eae80",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0d1ba9e0-6acf-4931-9478-791ccf883a47",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5af6161e-e723-4186-8c7e-13a562430b72",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "65b57dd0-e871-4bec-aaa0-2de8777b3884",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4aa43db7-2924-4a88-9f59-94333000c20e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "af53a123-ca4d-48b5-ada3-f148efbcc130",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "44bb05f5-3c39-4c0d-8b4f-fb68786464ee",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4539fa86-8b56-435c-838f-3463f57a5035",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "245e9782-9e65-48a2-afbc-d9eb996b0969",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6cffc5d0-fa96-40e6-8c99-d9afa2430e62",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9c610bdc-887e-49ba-9d3c-b1badd17d9eb",
                "ordinal": 3
              }
            ],
            "lineageTag": "28528c04-5e2f-49a1-a74d-4f6fc3f8f321"
          }
        ],
        "isHidden": true,
        "lineageTag": "eb467500-25b0-4557-bb7a-9f89add6d69a",
        "partitions": [
          {
            "name": "LocalDateTable_f608b07e-684f-49d7-9711-b443714e3eff-695a04d7-06d1-4a8d-aae3-cde21734e9d7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('systemlookup (2)'[createdAt])), 1, 1), Date(Year(MAX('systemlookup (2)'[createdAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_658449bb-c6b5-4f89-8062-310009421a53",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a0d3422a-2ffe-4626-8d56-074abb18fd7e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5ca32790-50a6-4ac2-a18b-b2eb0fa436e8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b4ee332c-c258-4b4a-8894-12a401e9f0dc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9d990cd9-a003-4406-ba34-afcc3e6165a9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2071a636-97c5-4eb3-9dfe-d35728632daf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ac3aad29-47fe-4827-888e-aac26b20883b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b7c25371-922f-4dfb-9c8f-3ac61146ea29",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0599c7f1-995d-4595-ac1a-1e01cd8a9956",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6e160054-5360-4d9f-8e81-76d830adf088",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b144457c-8eaa-4422-b879-848f96248c93",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d5dfc36d-84fa-4d72-9f5a-c41aece1414d",
                "ordinal": 3
              }
            ],
            "lineageTag": "015f91fa-ac4a-48e1-9f9d-fa36bc349114"
          }
        ],
        "isHidden": true,
        "lineageTag": "e64749fc-6393-47ed-b607-55d909da00a1",
        "partitions": [
          {
            "name": "LocalDateTable_658449bb-c6b5-4f89-8062-310009421a53-ccfecf29-90be-4581-91f9-b83159503bbf",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('systemlookup (2)'[updatedAt])), 1, 1), Date(Year(MAX('systemlookup (2)'[updatedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}