{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"asset\",\"department\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1805.0 (23.12)"
      },
      {
        "name": "__LastRPTime",
        "value": "133341862227473749"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "4a9c6631-25e1-40a0-9f66-3e7a6cbf6bb2",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "departmentId",
        "fromTable": "asset",
        "toColumn": "id",
        "toTable": "department"
      }
    ],
    "roles": [
      {
        "name": "ORG_LEVEL_SECURITY",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "db0bcc9c4e274a84aea55c617c6ceca9"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "asset",
            "filterExpression": "[org] = USERNAME()"
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "asset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isKey": true,
            "lineageTag": "e95952e5-9d0b-41c6-a582-708bd89beac9",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7194445-5fd1-4aa0-8678-6ccbe3f183af",
            "sourceColumn": "org",
            "summarizeBy": "none"
          },
          {
            "name": "riskScore",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "2409b51e-1340-44ed-8c53-54c5d10ab4b5",
            "sourceColumn": "riskScore",
            "summarizeBy": "sum"
          },
          {
            "name": "roundedRiskScore",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "expression": "MROUND(asset[riskScore],.5)",
            "isDataTypeInferred": true,
            "lineageTag": "4f513e64-450f-41a1-abad-ba76419f1ff2",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "departmentId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "050c323c-fdb4-4432-bc7c-85f8eacb748d",
            "sourceColumn": "departmentId",
            "summarizeBy": "none"
          },
          {
            "name": "calculatedDepartment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(ISBLANK(RELATED(department[id])), \"(No Department)\", RELATED(department[name]))",
            "isDataTypeInferred": true,
            "lineageTag": "9039963d-158d-43bc-a48a-b40543c29b70",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "7f939cb4-0ee6-4096-bbcf-58271c7b6b0f",
        "partitions": [
          {
            "name": "asset-71e480fb-85ef-4268-9b22-3e4b770bcfd4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"127.0.0.1,1433\"),",
                "    mentor_demo = Source{[Name=\"mentor_database\"]}[Data],",
                "    dbo_asset = mentor_demo{[Schema=\"dbo\",Item=\"asset\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_asset,{\"id\", \"org\", \"riskScore\", \"departmentId\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each [riskScore] <> null and [riskScore] <> \"\")",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_c82ddd71-bbe5-47e1-83b8-b8b62177d174",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "311cc022-14ca-489a-9b2a-671beeb4fa02",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "lineageTag": "69998ff4-82af-4d31-a529-59a1c1735bce",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "lineageTag": "62d71698-2ba0-4050-a85f-f2c3c4d13d04",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "38cf22b8-5379-4330-b6cb-1412732f62e4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "lineageTag": "25118880-b37d-4646-9d46-4cdc4293ba88",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "lineageTag": "f441a39d-f588-4dca-9129-96f700a8b724",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "lineageTag": "34c72c45-b131-4580-bbdc-fff5e4aab415",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4858daca-be33-4e90-8f54-9296837a4d46",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "46ddb1d1-f0b9-4c8c-83b0-1c9213b6ddb4",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8de622ea-25b7-4f97-804c-30c9fbc79f2b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "84814859-12b8-4ca2-a06f-8177aec06ae1",
                "ordinal": 3
              }
            ],
            "lineageTag": "80d150a1-ffd0-4539-81d5-1e25509618a8"
          }
        ],
        "isPrivate": true,
        "lineageTag": "5549c1e9-7a08-4481-abc2-a281e1450fbf",
        "partitions": [
          {
            "name": "DateTableTemplate_c82ddd71-bbe5-47e1-83b8-b8b62177d174-f05f8f9f-c69d-417b-b1bf-175a9b5a99ec",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "department",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "04fd08ed-35cf-4cb3-9c63-66a3ac8fdc3e",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f42fa03f-002d-4023-8d5f-05dd1a905325",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d226dd4-2b55-4115-a517-f9b23c586dc2",
            "sourceColumn": "org",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "30d65bc3-006e-4320-858f-1fd47cd8eef6",
        "partitions": [
          {
            "name": "department-53f15a82-7760-4f9a-a5ca-f1df0feb267b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"127.0.0.1,1433\"),",
                "    mentor_demo = Source{[Name=\"mentor_database\"]}[Data],",
                "    dbo_department = mentor_demo{[Schema=\"dbo\",Item=\"department\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_department,{\"id\", \"org\", \"name\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}