{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"asset\",\"department\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1805.0 (23.12)"
      },
      {
        "name": "__LastRPTime",
        "value": "133341862202411302"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "asset": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "asset"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "asset": {
                      "State": "Generated"
                    }
                  },
                  {
                    "strength": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "skill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "talent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "ability": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "qualification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "endowment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "advantage": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "benefit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "plus": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "quality": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "asset.calculated_department": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "asset",
                    "ConceptualProperty": "calculatedDepartment"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "calculated department": {
                      "State": "Generated"
                    }
                  },
                  {
                    "calculatedDepartment": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "calculated subdivision": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "calculated division": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "calculated unit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "calculated section": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "calculated branch": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "calculated sector": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "calculated responsibility": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "calculated specialty": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "calculated realm": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "calculated area": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  }
                ]
              },
              "asset.criticality_score": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "asset",
                    "ConceptualProperty": "criticalityScore"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "criticality score": {
                      "State": "Generated"
                    }
                  },
                  {
                    "criticalityScore": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "score": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "criticality notch": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "criticality slash": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "criticality groove": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "criticality nick": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "criticality cut": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "criticality mark": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "notch": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "slash": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "groove": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "nick": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "asset.department_id": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "asset",
                    "ConceptualProperty": "departmentId"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "department id": {
                      "State": "Generated"
                    }
                  },
                  {
                    "departmentId": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "department identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "department identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "department identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "department credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "asset.id": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "asset",
                    "ConceptualProperty": "id"
                  }
                },
                "NameType": "Identifier",
                "State": "Generated",
                "Terms": [
                  {
                    "id": {
                      "State": "Generated"
                    }
                  },
                  {
                    "identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "asset.org": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "asset",
                    "ConceptualProperty": "org"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "org": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "asset.rounded_criticality_score": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "asset",
                    "ConceptualProperty": "roundedCriticalityScore"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "rounded criticality score": {}
                  },
                  {
                    "roundedCriticalityScore": {
                      "LastModified": "2024-01-23T19:23:32.122Z",
                      "State": "Deleted",
                      "Type": "Noun"
                    }
                  },
                  {
                    "score": {
                      "LastModified": "2024-01-23T19:23:32.122Z",
                      "State": "Deleted"
                    }
                  },
                  {
                    "rounded criticality notch": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "rounded criticality slash": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "rounded criticality groove": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "rounded criticality nick": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "rounded criticality cut": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "rounded criticality mark": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "notch": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "slash": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "groove": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "nick": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "department": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "department"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "department": {
                      "State": "Generated"
                    }
                  },
                  {
                    "subdivision": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "division": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "unit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "section": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "branch": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "sector": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "responsibility": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "specialty": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "realm": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "area": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "department.id": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "department",
                    "ConceptualProperty": "id"
                  }
                },
                "NameType": "Identifier",
                "State": "Generated",
                "Terms": [
                  {
                    "id": {
                      "State": "Generated"
                    }
                  },
                  {
                    "identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "department.name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "department",
                    "ConceptualProperty": "name"
                  }
                },
                "NameType": "Name",
                "State": "Generated",
                "Terms": [
                  {
                    "name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "department.org": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "department",
                    "ConceptualProperty": "org"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "org": {
                      "State": "Generated"
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "asset_has_calculated_department": {
                "Binding": {
                  "ConceptualEntity": "asset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "asset.calculated_department"
                      },
                      "Subject": {
                        "Role": "asset"
                      }
                    },
                    "ID": "assets_have_calculated_departments",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "asset": {
                    "Target": {
                      "Entity": "asset"
                    }
                  },
                  "asset.calculated_department": {
                    "Target": {
                      "Entity": "asset.calculated_department"
                    }
                  }
                },
                "State": "Generated"
              },
              "asset_has_criticality_score": {
                "Binding": {
                  "ConceptualEntity": "asset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "asset.criticality_score"
                      },
                      "Subject": {
                        "Role": "asset"
                      }
                    },
                    "ID": "assets_have_criticality_scores",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "asset": {
                    "Target": {
                      "Entity": "asset"
                    }
                  },
                  "asset.criticality_score": {
                    "Target": {
                      "Entity": "asset.criticality_score"
                    }
                  }
                },
                "State": "Generated"
              },
              "asset_has_department": {
                "Binding": {
                  "ConceptualEntity": "asset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "department"
                      },
                      "Subject": {
                        "Role": "asset"
                      }
                    },
                    "ID": "assets_have_departments",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "asset"
                      },
                      "Subject": {
                        "Role": "department"
                      }
                    },
                    "ID": "departments_have_assets",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "asset": {
                    "Target": {
                      "Entity": "asset"
                    }
                  },
                  "department": {
                    "Target": {
                      "Entity": "department"
                    }
                  }
                },
                "State": "Generated"
              },
              "asset_has_org": {
                "Binding": {
                  "ConceptualEntity": "asset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "asset.org"
                      },
                      "Subject": {
                        "Role": "asset"
                      }
                    },
                    "ID": "assets_have_org",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "asset": {
                    "Target": {
                      "Entity": "asset"
                    }
                  },
                  "asset.org": {
                    "Target": {
                      "Entity": "asset.org"
                    }
                  }
                },
                "State": "Generated"
              },
              "asset_has_rounded_criticality_score": {
                "Binding": {
                  "ConceptualEntity": "asset"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "asset.rounded_criticality_score"
                      },
                      "Subject": {
                        "Role": "asset"
                      }
                    },
                    "ID": "assets_have_rounded_criticality_scores",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "asset": {
                    "Target": {
                      "Entity": "asset"
                    }
                  },
                  "asset.rounded_criticality_score": {
                    "Target": {
                      "Entity": "asset.rounded_criticality_score"
                    }
                  }
                },
                "State": "Generated"
              },
              "asset_is_named_id": {
                "Binding": {
                  "ConceptualEntity": "asset"
                },
                "Phrasings": [
                  {
                    "ID": "ids_are_names_IDs_of_assets",
                    "Name": {
                      "Name": {
                        "Role": "asset.id"
                      },
                      "Subject": {
                        "Role": "asset"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "asset.id"
                      },
                      "Subject": {
                        "Role": "asset"
                      }
                    },
                    "ID": "assets_have_ids",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "asset": {
                    "Target": {
                      "Entity": "asset"
                    }
                  },
                  "asset.id": {
                    "Target": {
                      "Entity": "asset.id"
                    }
                  }
                },
                "State": "Generated"
              },
              "department_has_org": {
                "Binding": {
                  "ConceptualEntity": "department"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "department.org"
                      },
                      "Subject": {
                        "Role": "department"
                      }
                    },
                    "ID": "departments_have_org",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "department": {
                    "Target": {
                      "Entity": "department"
                    }
                  },
                  "department.org": {
                    "Target": {
                      "Entity": "department.org"
                    }
                  }
                },
                "State": "Generated"
              },
              "department_is_named_id": {
                "Binding": {
                  "ConceptualEntity": "department"
                },
                "Phrasings": [
                  {
                    "ID": "ids_are_names_IDs_of_departments",
                    "Name": {
                      "Name": {
                        "Role": "department.id"
                      },
                      "Subject": {
                        "Role": "department"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "department.id"
                      },
                      "Subject": {
                        "Role": "department"
                      }
                    },
                    "ID": "departments_have_ids",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "department": {
                    "Target": {
                      "Entity": "department"
                    }
                  },
                  "department.id": {
                    "Target": {
                      "Entity": "department.id"
                    }
                  }
                },
                "State": "Generated"
              },
              "department_is_named_name": {
                "Binding": {
                  "ConceptualEntity": "department"
                },
                "Phrasings": [
                  {
                    "ID": "names_are_names_IDs_of_departments",
                    "Name": {
                      "Name": {
                        "Role": "department.name"
                      },
                      "Subject": {
                        "Role": "department"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "department.name"
                      },
                      "Subject": {
                        "Role": "department"
                      }
                    },
                    "ID": "departments_have_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "department": {
                    "Target": {
                      "Entity": "department"
                    }
                  },
                  "department.name": {
                    "Target": {
                      "Entity": "department.name"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "d82659ab-b6c1-429f-9ff0-d2a59c083b21",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "departmentId",
        "fromTable": "asset",
        "toColumn": "id",
        "toTable": "department"
      }
    ],
    "roles": [
      {
        "name": "ORG_LEVEL_SECURITY",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "54fd084f6b5f40449ba5f2b74e10d37a"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "asset",
            "filterExpression": "asset[org] = USERNAME()"
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "asset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e95952e5-9d0b-41c6-a582-708bd89beac9",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7194445-5fd1-4aa0-8678-6ccbe3f183af",
            "sourceColumn": "org",
            "summarizeBy": "none"
          },
          {
            "name": "criticalityScore",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8f24ea54-f9fe-4993-90d3-f13a6ca66669",
            "sourceColumn": "criticalityScore",
            "summarizeBy": "sum"
          },
          {
            "name": "departmentId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d15845d6-0215-4937-9b7b-42d670dda246",
            "sourceColumn": "departmentId",
            "summarizeBy": "none"
          },
          {
            "name": "roundedCriticalityScore",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "MROUND(asset[criticalityScore],.5)",
            "isDataTypeInferred": true,
            "lineageTag": "5883a1d7-91a8-4348-af46-6dfadce22a1e",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "calculatedDepartment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(ISBLANK(RELATED(department[id])), \"(No Department)\", RELATED(department[name]))",
            "isDataTypeInferred": true,
            "lineageTag": "200cdf7a-37b6-4b65-a450-1481137628b4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "7f939cb4-0ee6-4096-bbcf-58271c7b6b0f",
        "partitions": [
          {
            "name": "asset-71e480fb-85ef-4268-9b22-3e4b770bcfd4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"127.0.0.1,1433\"),",
                "    mentor_demo = Source{[Name=\"mentor_database\"]}[Data],",
                "    dbo_asset = mentor_demo{[Schema=\"dbo\",Item=\"asset\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_asset,{\"id\", \"org\", \"criticalityScore\", \"departmentId\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each [criticalityScore] <> null and [criticalityScore] <> \"\")",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_c82ddd71-bbe5-47e1-83b8-b8b62177d174",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "311cc022-14ca-489a-9b2a-671beeb4fa02",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "69998ff4-82af-4d31-a529-59a1c1735bce",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "62d71698-2ba0-4050-a85f-f2c3c4d13d04",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "38cf22b8-5379-4330-b6cb-1412732f62e4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "25118880-b37d-4646-9d46-4cdc4293ba88",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f441a39d-f588-4dca-9129-96f700a8b724",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "34c72c45-b131-4580-bbdc-fff5e4aab415",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4858daca-be33-4e90-8f54-9296837a4d46",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "46ddb1d1-f0b9-4c8c-83b0-1c9213b6ddb4",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8de622ea-25b7-4f97-804c-30c9fbc79f2b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "84814859-12b8-4ca2-a06f-8177aec06ae1",
                "ordinal": 3
              }
            ],
            "lineageTag": "80d150a1-ffd0-4539-81d5-1e25509618a8"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "5549c1e9-7a08-4481-abc2-a281e1450fbf",
        "partitions": [
          {
            "name": "DateTableTemplate_c82ddd71-bbe5-47e1-83b8-b8b62177d174-f05f8f9f-c69d-417b-b1bf-175a9b5a99ec",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "department",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04fd08ed-35cf-4cb3-9c63-66a3ac8fdc3e",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f42fa03f-002d-4023-8d5f-05dd1a905325",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d226dd4-2b55-4115-a517-f9b23c586dc2",
            "sourceColumn": "org",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "30d65bc3-006e-4320-858f-1fd47cd8eef6",
        "partitions": [
          {
            "name": "department-53f15a82-7760-4f9a-a5ca-f1df0feb267b",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"127.0.0.1,1433\"),",
                "    mentor_demo = Source{[Name=\"mentor_database\"]}[Data],",
                "    dbo_department = mentor_demo{[Schema=\"dbo\",Item=\"department\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_department,{\"id\", \"name\", \"org\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}