{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.1063.0 (23.06)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"workstage\",\"department\",\"role\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "__LastRPTime",
        "value": "133341861930255628"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "4f77e9ec-3676-4c65-880b-197ce33fa22a",
        "fromColumn": "statusDate",
        "fromTable": "workstage",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c7715471-8ca8-48c9-8ae8-2e42cd5c8799"
      },
      {
        "name": "f6fc64a1-62dd-4f7b-a7fe-86c0dc52bc5f",
        "fromColumn": "createdAt",
        "fromTable": "department",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_81a5318b-7239-4a82-b9b2-69afb36ae3f9"
      },
      {
        "name": "9b6243d3-e2ee-4b3e-8ee1-8b54656fc2f9",
        "fromColumn": "updatedAt",
        "fromTable": "department",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_58a5a9c4-fba6-4941-823c-06d3b01aef4e"
      },
      {
        "name": "fc95bd09-833a-404a-866e-0564788a99fd",
        "fromColumn": "createdAt",
        "fromTable": "role",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_226b7b46-ef65-4fac-802a-aa4406e1f54c"
      },
      {
        "name": "61ef8500-89dc-4504-bfb6-2b77949f0fd7",
        "fromColumn": "updatedAt",
        "fromTable": "role",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8a0919c8-f7d1-478b-91ad-e96dd0643374"
      },
      {
        "name": "4db750b8-65e9-47fc-9698-a3e3081ba6dd",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "departmentId",
        "fromTable": "workstage",
        "toColumn": "id",
        "toTable": "department"
      },
      {
        "name": "b14bb7ed-4382-4cd3-8d44-0a601b48fb2c",
        "fromColumn": "Close Date",
        "fromTable": "workstage",
        "toColumn": "Date",
        "toTable": "Calendar"
      }
    ],
    "roles": [
      {
        "name": "ORG_LEVEL_SECURITY",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5bf342468fc245bbb47acd8a6e8fb846"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "workstage",
            "filterExpression": "workstage[org] = USERNAME()"
          },
          {
            "name": "role",
            "filterExpression": "role[org] = USERNAME()"
          },
          {
            "name": "department",
            "filterExpression": "department[org] = USERNAME()"
          }
        ]
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "workstage",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "beede4c0-1bfe-4104-b096-90ae6c4bf339",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c92dae35-85d5-459a-8ba6-7ceff0007710",
            "sourceColumn": "org",
            "summarizeBy": "none"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d466107a-28eb-4d61-851d-175ba475e2c1",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "statusDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9e28e874-8a52-474f-9739-53fd0b0038b4",
            "sourceColumn": "statusDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c7715471-8ca8-48c9-8ae8-2e42cd5c8799"
                },
                "isDefault": true,
                "relationship": "4f77e9ec-3676-4c65-880b-197ce33fa22a"
              }
            ]
          },
          {
            "name": "departmentId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "629a8cc4-d374-4946-a82e-5b1f19eda836",
            "sourceColumn": "departmentId",
            "summarizeBy": "none"
          },
          {
            "name": "Close Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": "DATE(YEAR(workstage[statusDate]), MONTH(workstage[statusDate]), DAY(workstage[statusDate]))",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "610c1a32-2b45-4a8e-aac6-1f764a292931",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "1af9f56f-3711-4bfd-9590-a5da6184956f",
        "partitions": [
          {
            "name": "workstage-18635680-d054-470e-8c09-fee6573cc5c2",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"127.0.0.1,1433\", \"mentor_database\"),",
                "    dbo_workstage = Source{[Schema=\"dbo\",Item=\"workstage\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_workstage,{\"captureConditionScore\", \"desc\", \"altId\", \"parent\", \"level\", \"node\"}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Removed Columns\",{\"id\", \"org\", \"status\", \"statusDate\", \"departmentId\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Removed Other Columns\", each ([status] = \"Canceled\" or [status] = \"Complete\"))",
                "in",
                "    #\"Filtered Rows\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_a50d6794-8b0a-4d11-b1b9-8209b90c5075",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c3118834-aca0-45e1-a2b3-eae404557aad",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "56895ea2-9d5d-4670-bdf4-ae83af736789",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6097489f-c2a8-4431-a810-2ac103ad468b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "58acd6b0-dd14-4bb3-abeb-9a29c7ef2173",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2ccff054-23c0-4c75-a744-8e043d4dc5f0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "77eabe4d-58f5-46c7-a628-b55c9e9bdd1e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e5f88a3f-5a64-40de-9d41-df5b728b3f1f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b013c462-fb18-428a-9d74-9e79c35f14a6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9fb36ff8-21d0-474f-8ea6-358e8533d8d8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f39935ea-72a4-4dcb-a301-404d9d3fca0d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ebffd736-c939-4ff9-a389-b06332199936",
                "ordinal": 3
              }
            ],
            "lineageTag": "7d2dd7bb-90d3-42c4-816a-e61dafe93aac"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "204c0d7b-99e7-4a29-b223-00180e95851f",
        "partitions": [
          {
            "name": "DateTableTemplate_a50d6794-8b0a-4d11-b1b9-8209b90c5075-680e49e7-9a8f-42c5-b5bb-da226503830e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c7715471-8ca8-48c9-8ae8-2e42cd5c8799",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a79c6248-8345-4f55-803b-f6a612be1768",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "25aa402c-92c2-4a48-9824-bda38ae4a1fd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fe10210d-b285-4daa-acb0-53efc57faba4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "64dd2dc4-25b2-4078-8684-11f3edca6622",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "da57e931-f6ca-4a7c-a579-c6fd687e06e7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fdaf092a-a45d-498c-b4a4-a5afa5e9ec22",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "231ac808-4ff3-448a-a1d3-a027469c209b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4f243c1e-0967-4ccd-9786-9fbb3eaaf00b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6b9ac992-88d5-4f2d-8735-91b268a24eae",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c1c95fe4-981b-4ee7-ba4e-bb763859c47e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "87884f4c-7e5d-4a92-92f9-60de7187ef8e",
                "ordinal": 3
              }
            ],
            "lineageTag": "22ced380-4e7a-443e-94a5-c8627fa90130"
          }
        ],
        "isHidden": true,
        "lineageTag": "6c61940d-e7b0-41e1-9b74-2e8517992151",
        "partitions": [
          {
            "name": "LocalDateTable_c7715471-8ca8-48c9-8ae8-2e42cd5c8799-6381ce49-483e-4ec5-a2ea-c6594e0db51a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('workstage'[statusDate])), 1, 1), Date(Year(MAX('workstage'[statusDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "department",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4cf28a4b-5696-407b-bc68-0b57e189baeb",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74e18b97-f426-4bc5-882f-aa53c6b33115",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a848ff0-41ea-43bf-bf93-5062ecc1de24",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "createdAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9437f8c2-0740-4d1b-becc-c95238a498a4",
            "sourceColumn": "createdAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_81a5318b-7239-4a82-b9b2-69afb36ae3f9"
                },
                "isDefault": true,
                "relationship": "f6fc64a1-62dd-4f7b-a7fe-86c0dc52bc5f"
              }
            ]
          },
          {
            "name": "updatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "21bad155-dc28-46ac-b995-018278cbc520",
            "sourceColumn": "updatedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_58a5a9c4-fba6-4941-823c-06d3b01aef4e"
                },
                "isDefault": true,
                "relationship": "9b6243d3-e2ee-4b3e-8ee1-8b54656fc2f9"
              }
            ]
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "158a4bae-12df-4acd-ad90-93ccae998c05",
            "sourceColumn": "org",
            "summarizeBy": "none"
          },
          {
            "name": "laborOffsetAccount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43599464-ff6b-4a6a-bd28-c2f4b3f0a2f1",
            "sourceColumn": "laborOffsetAccount",
            "summarizeBy": "none"
          },
          {
            "name": "laborOffsetExpenditureType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96805194-269c-4fc9-9cd9-227a9cf410ed",
            "sourceColumn": "laborOffsetExpenditureType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6f7ff4ca-0213-4655-b688-a520283718eb",
        "partitions": [
          {
            "name": "department-fa2f3dbd-03e4-447f-82bf-277bc237fde6",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"127.0.0.1,1433\", \"mentor_database\"),",
                "    dbo_department = Source{[Schema=\"dbo\",Item=\"department\"]}[Data]",
                "in",
                "    dbo_department"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_81a5318b-7239-4a82-b9b2-69afb36ae3f9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0c9ba8f0-cced-47f8-bcff-cc9c0a62551d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6917562d-979f-459c-98a3-4233b2dcd3ed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "417fa2b7-04dd-4485-8b1d-6ef00b8230d0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "31a63b7a-984a-4588-a6e0-4a625dee9337",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2d53771d-bde6-40c2-ae46-e6fdc568c3b4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "938f9f43-1bdb-4017-bb94-02b60e17f7f9",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "46527551-db49-4372-9544-9be348f04cfd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3da54200-e58e-4857-b568-81e9876f2017",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7d274a9c-b0fe-4ce0-b5aa-2c437d71cea8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "613db16a-17d5-44cb-9706-04d2b9dd7ef1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "13c50a65-35d0-4551-822b-2b6665cae181",
                "ordinal": 3
              }
            ],
            "lineageTag": "da1919e4-5584-4afc-8731-d44b49da236c"
          }
        ],
        "isHidden": true,
        "lineageTag": "ef7e656a-0ebd-40cd-a474-dfc68c4445eb",
        "partitions": [
          {
            "name": "LocalDateTable_81a5318b-7239-4a82-b9b2-69afb36ae3f9-d1e1ba29-d567-4757-99aa-77a91aad0674",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('department'[createdAt])), 1, 1), Date(Year(MAX('department'[createdAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_58a5a9c4-fba6-4941-823c-06d3b01aef4e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f54565cf-33de-48df-9280-36fb30fdfed7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5477da72-cc4c-48a6-974b-63b7d287c3b1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5c78bdc1-0bd8-4e9c-9474-ef1476e2ad34",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ad5dbea6-61e4-4589-9b74-d2a3e32132d5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b1e0243c-a429-46bd-937c-3620ce9745bd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "02add8e6-91a3-4673-befc-17ece62e8ab1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f09be00a-a03b-43f7-9d33-741fb1e60335",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "eac6f006-4f24-4518-8147-03b6470c78d1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c2ba0ddf-c5af-4c9c-8a38-b5e693eb86d2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3ad62634-e3cc-42e5-be43-4f5a21ee7057",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "93ae7a2a-59c9-4df2-b689-d8282828bd3d",
                "ordinal": 3
              }
            ],
            "lineageTag": "0afe34e0-bd1e-4cb7-8f30-3508522f35e9"
          }
        ],
        "isHidden": true,
        "lineageTag": "715c820d-33aa-42c8-bff0-a7958c657451",
        "partitions": [
          {
            "name": "LocalDateTable_58a5a9c4-fba6-4941-823c-06d3b01aef4e-26f7b173-6a8a-403f-b261-fe87fd26788c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('department'[updatedAt])), 1, 1), Date(Year(MAX('department'[updatedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "role",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "387232aa-bf8b-4c8c-8175-a5b2df87aa18",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "org",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c64b9666-e8fa-4730-a102-54d6ecb0ed08",
            "sourceColumn": "org",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42a3204b-6b68-4ab2-b7cd-e0595be47bb1",
            "sourceColumn": "name",
            "summarizeBy": "none"
          },
          {
            "name": "desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8f63f84-e979-49f0-8e93-9bab7a658ae5",
            "sourceColumn": "desc",
            "summarizeBy": "none"
          },
          {
            "name": "whiteboardMode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eabe3e33-5146-4285-bba1-0ef5ab0eee64",
            "sourceColumn": "whiteboardMode",
            "summarizeBy": "none"
          },
          {
            "name": "createdAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "31092046-c874-477a-8a0f-a61040a0e090",
            "sourceColumn": "createdAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_226b7b46-ef65-4fac-802a-aa4406e1f54c"
                },
                "isDefault": true,
                "relationship": "fc95bd09-833a-404a-866e-0564788a99fd"
              }
            ]
          },
          {
            "name": "updatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "60617d66-6a47-4ec7-b07c-cfb21696a29d",
            "sourceColumn": "updatedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_8a0919c8-f7d1-478b-91ad-e96dd0643374"
                },
                "isDefault": true,
                "relationship": "61ef8500-89dc-4504-bfb6-2b77949f0fd7"
              }
            ]
          },
          {
            "name": "dataStoreId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "333147db-debc-4904-a9c7-bb6968ae031d",
            "sourceColumn": "dataStoreId",
            "summarizeBy": "none"
          },
          {
            "name": "foreignId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2c966f0-f0a6-4ce3-9cee-bb75d9a65e39",
            "sourceColumn": "foreignId",
            "summarizeBy": "none"
          },
          {
            "name": "color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74c07cd1-bd51-4590-aa2e-51956fc399ab",
            "sourceColumn": "color",
            "summarizeBy": "none"
          },
          {
            "name": "whiteboardLayout",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfc775d0-463f-4c64-bcec-cc97da6391b2",
            "sourceColumn": "whiteboardLayout",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6617e475-5349-4c70-bae7-673586303f43",
        "partitions": [
          {
            "name": "role-65c7b4d6-31e8-4ca4-84cf-2af2852f3202",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"127.0.0.1,1433\", \"mentor_database\"),",
                "    dbo_role = Source{[Schema=\"dbo\",Item=\"role\"]}[Data]",
                "in",
                "    dbo_role"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_226b7b46-ef65-4fac-802a-aa4406e1f54c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "60421ae9-e862-4c8d-aaaa-2bddbea6fa23",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0c2dbfde-1623-430e-9942-f9a3e96661ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ec415d53-b5e4-4f12-b15f-c2b041227d59",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8b994028-424b-47f4-9753-43498e682f7b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "245bd615-fa6a-449b-8a69-5441ec9cdae6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "10f6606a-2f71-4ac4-bb7c-f7d4c7d39259",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1d7084dc-e394-4dc0-a71c-597c7898542c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a5987eb3-2b26-488e-a6f7-cccaf5394cf1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "27a5ab1f-6f83-40ad-9dca-114b6ee32887",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5802c08c-927d-477b-b567-b868e2e36335",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3a0007f1-aca3-4a0a-9a0d-8fc0e20ccaac",
                "ordinal": 3
              }
            ],
            "lineageTag": "9dda8587-f157-41b6-9119-25c370a70c49"
          }
        ],
        "isHidden": true,
        "lineageTag": "297d3c2f-9a56-4431-9a9d-4c1746d7619c",
        "partitions": [
          {
            "name": "LocalDateTable_226b7b46-ef65-4fac-802a-aa4406e1f54c-89b1210b-b0b8-408f-b3a2-7d2a8bae8dc2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('role'[createdAt])), 1, 1), Date(Year(MAX('role'[createdAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_8a0919c8-f7d1-478b-91ad-e96dd0643374",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a0813005-1c59-47f3-8b64-87251a0011d0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "508f6821-6a09-4153-be05-a1976c7ae785",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7505faa0-4831-4828-a131-ae4ffc6bad5d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "46145b5e-9782-4b4d-bc05-f524f5378046",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "66ec15f5-ed97-418c-8f1f-79c33801936e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "76816102-4a37-49f7-b097-8263a66ef2f0",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ed51375e-7f23-4128-a1ab-e986790f45b7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "08c8c90d-fb49-4655-a804-acf88a476fb0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e0064680-55a4-4c94-811f-efc554451a1e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "cd648a33-ecc8-4b67-bf9b-0cfae11a309c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "82644808-61ce-4f84-ba63-f3bec32347bb",
                "ordinal": 3
              }
            ],
            "lineageTag": "52a7f1ec-5379-4f4c-92e2-91fec9ec8e25"
          }
        ],
        "isHidden": true,
        "lineageTag": "93abcfdb-2c01-4eb9-aa60-620cd15fc233",
        "partitions": [
          {
            "name": "LocalDateTable_8a0919c8-f7d1-478b-91ad-e96dd0643374-9194ed93-a820-4df3-9482-dc8b02e0e43e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('role'[updatedAt])), 1, 1), Date(Year(MAX('role'[updatedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ea445384aad643aa8be63ed642894815"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "6ab70ffc-9647-4f06-9811-41da1b12384c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR('Calendar'[Date])",
            "formatString": "0",
            "lineageTag": "fb1b75b6-35e1-46e9-893f-7823163eb2da",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('Calendar'[Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "lineageTag": "af1d6572-8fe0-465e-8926-0e0a7455972e",
            "sortByColumn": "MonthNumber",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DAY('Calendar'[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "e8a8bfe7-ffa0-4e1b-b9db-e42c603ed4ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": "(MONTH('Calendar'[Date]))",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3fd58c31-e47d-4756-b6cf-e773c3e319fc",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "607fd61f-d9c6-4f32-9440-a7c26ee1f5bf",
                "ordinal": 0
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3abd28be-f90a-4586-a4c1-11670eaea344",
                "ordinal": 1
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8f1b7b81-bd04-40cd-afe2-1e9b8f654c13",
                "ordinal": 2
              }
            ],
            "lineageTag": "b0376de4-6df0-4307-9bfd-c05a7baad1a7"
          }
        ],
        "lineageTag": "b6da639e-2ec3-45c4-895b-d5e967e9be95",
        "measures": [
          {
            "name": "TableTitle",
            "expression": [
              "",
              "var YearVal = SELECTEDVALUE('Calendar'[Year], \"All Years\")",
              "var MonthVal = IF(",
              "    ISFILTERED('Calendar'[Month]),",
              "    SELECTEDVALUE('Calendar'[Month]) & \" \",",
              "     \"\")",
              "return",
              "\"Closed Work for \" & MonthVal & YearVal"
            ],
            "lineageTag": "d0bf00d9-2641-4fd5-b2e4-71d714e554c3"
          }
        ],
        "partitions": [
          {
            "name": "Calendar-9592a581-62cd-4b5c-84b7-9825cbdb9460",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(DATE(YEAR(TODAY()) - 2, 1, 1), DATE(YEAR(TODAY()) + 2, 12, 31))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}